// 🖼️ Hero Icons - MLBB PerfectPick v3.2
// Imágenes almacenadas localmente (sin dependencia externa)
// Total: 144 héroes disponibles
// Última actualización: 2025-10-15

const heroIcons = [
    { name: 'Miya', icon: 'img/heroes/hero011.png' },
    { name: 'Balmond', icon: 'img/heroes/hero021.png' },
    { name: 'Saber', icon: 'img/heroes/hero031.png' },
    { name: 'Alice', icon: 'img/heroes/hero041.png' },
    { name: 'Nana', icon: 'img/heroes/hero051.png' },
    { name: 'Tigreal', icon: 'img/heroes/hero061.png' },
    { name: 'Alucard', icon: 'img/heroes/hero071.png' },
    { name: 'Karina', icon: 'img/heroes/hero081.png' },
    { name: 'Akai', icon: 'img/heroes/hero091.png' },
    { name: 'Franco', icon: 'img/heroes/hero101.png' },
    { name: 'Bane', icon: 'img/heroes/hero111.png' },
    { name: 'Bruno', icon: 'img/heroes/hero121.png' },
    { name: 'Clint', icon: 'img/heroes/hero131.png' },
    { name: 'Rafaela', icon: 'img/heroes/hero141.png' },
    { name: 'Eudora', icon: 'img/heroes/hero151.png' },
    { name: 'Zilong', icon: 'img/heroes/hero161.png' },
    { name: 'Fanny', icon: 'img/heroes/hero171.png' },
    { name: 'Layla', icon: 'img/heroes/hero181.png' },
    { name: 'Minotaur', icon: 'img/heroes/hero191.png' },
    { name: 'Lolita', icon: 'img/heroes/hero201.png' },
    { name: 'Hayabusa', icon: 'img/heroes/hero211.png' },
    { name: 'Freya', icon: 'img/heroes/hero221.png' },
    { name: 'Gord', icon: 'img/heroes/hero231.png' },
    { name: 'Natalia', icon: 'img/heroes/hero241.png' },
    { name: 'Kagura', icon: 'img/heroes/hero251.png' },
    { name: 'Chou', icon: 'img/heroes/hero261.png' },
    { name: 'Sun', icon: 'img/heroes/hero271.png' },
    { name: 'Alpha', icon: 'img/heroes/hero281.png' },
    { name: 'Ruby', icon: 'img/heroes/hero291.png' },
    { name: 'Yi Sun-shin', icon: 'img/heroes/hero301.png' },
    { name: 'Moskov', icon: 'img/heroes/hero311.png' },
    { name: 'Johnson', icon: 'img/heroes/hero321.png' },
    { name: 'Cyclops', icon: 'img/heroes/hero331.png' },
    { name: 'Estes', icon: 'img/heroes/hero341.png' },
    { name: 'Hilda', icon: 'img/heroes/hero351.png' },
    { name: 'Aurora', icon: 'img/heroes/hero361.png' },
    { name: 'Lapu-Lapu', icon: 'img/heroes/hero371.png' },
    { name: 'Vexana', icon: 'img/heroes/hero381.png' },
    { name: 'Roger', icon: 'img/heroes/hero391.png' },
    { name: 'Karrie', icon: 'img/heroes/hero401.png' },
    { name: 'Gatotkaca', icon: 'img/heroes/hero411.png' },
    { name: 'Harley', icon: 'img/heroes/hero421.png' },
    { name: 'Irithel', icon: 'img/heroes/hero431.png' },
    { name: 'Grock', icon: 'img/heroes/hero441.png' },
    { name: 'Argus', icon: 'img/heroes/hero451.png' },
    { name: 'Odette', icon: 'img/heroes/hero461.png' },
    { name: 'Lancelot', icon: 'img/heroes/hero471.png' },
    { name: 'Diggie', icon: 'img/heroes/hero481.png' },
    { name: 'Hylos', icon: 'img/heroes/hero491.png' },
    { name: 'Hylos', icon: 'img/heroes/hero491.png' },
    { name: 'Zhask', icon: 'img/heroes/hero501.png' },
    { name: 'Zhask', icon: 'img/heroes/hero501.png' },
    { name: 'Helcurt', icon: 'img/heroes/hero511.png' },
    { name: 'Helcurt', icon: 'img/heroes/hero511.png' },
    { name: 'Pharsa', icon: 'img/heroes/hero521.png' },
    { name: 'Pharsa', icon: 'img/heroes/hero521.png' },
    { name: 'Lesley', icon: 'img/heroes/hero531.png' },
    { name: 'Lesley', icon: 'img/heroes/hero531.png' },
    { name: 'Jawhead', icon: 'img/heroes/hero541.png' },
    { name: 'Jawhead', icon: 'img/heroes/hero541.png' },
    { name: 'Angela', icon: 'img/heroes/hero551.png' },
    { name: 'Angela', icon: 'img/heroes/hero551.png' },
    { name: 'Gusion', icon: 'img/heroes/hero561.png' },
    { name: 'Gusion', icon: 'img/heroes/hero561.png' },
    { name: 'Valir', icon: 'img/heroes/hero571.png' },
    { name: 'Valir', icon: 'img/heroes/hero571.png' },
    { name: 'Martis', icon: 'img/heroes/hero581.png' },
    { name: 'Martis', icon: 'img/heroes/hero581.png' },
    { name: 'Uranus', icon: 'img/heroes/hero591.png' },
    { name: 'Uranus', icon: 'img/heroes/hero591.png' },
    { name: 'Hanabi', icon: 'img/heroes/hero601.png' },
    { name: 'Hanabi', icon: 'img/heroes/hero601.png' },
    { name: 'Chang\'e', icon: 'img/heroes/hero611.png' },
    { name: 'Chang\'e', icon: 'img/heroes/hero611.png' },
    { name: 'Kaja', icon: 'img/heroes/hero621.png' },
    { name: 'Kaja', icon: 'img/heroes/hero621.png' },
    { name: 'Selena', icon: 'img/heroes/hero631.png' },
    { name: 'Aldous', icon: 'img/heroes/hero641.png' },
    { name: 'Claude', icon: 'img/heroes/hero651.png' },
    { name: 'Vale', icon: 'img/heroes/hero661.png' },
    { name: 'Leomord', icon: 'img/heroes/hero671.png' },
    { name: 'Lunox', icon: 'img/heroes/hero681.png' },
    { name: 'Hanzo', icon: 'img/heroes/hero691.png' },
    { name: 'Belerick', icon: 'img/heroes/hero701.png' },
    { name: 'Kimmy', icon: 'img/heroes/hero711.png' },
    { name: 'Thamuz', icon: 'img/heroes/hero721.png' },
    { name: 'Harith', icon: 'img/heroes/hero731.png' },
    { name: 'Minsitthar', icon: 'img/heroes/hero741.png' },
    { name: 'Kadita', icon: 'img/heroes/hero751.png' },
    { name: 'Faramis', icon: 'img/heroes/hero761.png' },
    { name: 'Badang', icon: 'img/heroes/hero771.png' },
    { name: 'Khufra', icon: 'img/heroes/hero781.png' },
    { name: 'Granger', icon: 'img/heroes/hero791.png' },
    { name: 'Guinevere', icon: 'img/heroes/hero801.png' },
    { name: 'Esmeralda', icon: 'img/heroes/hero811.png' },
    { name: 'Terizla', icon: 'img/heroes/hero821.png' },
    { name: 'X.Borg', icon: 'img/heroes/hero831.png' },
    { name: 'Ling', icon: 'img/heroes/hero841.png' },
    { name: 'Dyrroth', icon: 'img/heroes/hero851.png' },
    { name: 'Lylia', icon: 'img/heroes/hero861.png' },
    { name: 'Baxia', icon: 'img/heroes/hero871.png' },
    { name: 'Masha', icon: 'img/heroes/hero881.png' },
    { name: 'Wanwan', icon: 'img/heroes/hero891.png' },
    { name: 'Silvanna', icon: 'img/heroes/hero901.png' },
    { name: 'Cecilion', icon: 'img/heroes/hero911.png' },
    { name: 'Carmilla', icon: 'img/heroes/hero921.png' },
    { name: 'Atlas', icon: 'img/heroes/hero931.png' },
    { name: 'Popol y Kupa', icon: 'img/heroes/hero941.png' },
    { name: 'Yu Zhong', icon: 'img/heroes/hero951.png' },
    { name: 'Luo Yi', icon: 'img/heroes/hero961.png' },
    { name: 'Benedetta', icon: 'img/heroes/hero971.png' },
    { name: 'Khaleed', icon: 'img/heroes/hero981.png' },
    { name: 'Barats', icon: 'img/heroes/hero991.png' },
    { name: 'Brody', icon: 'img/heroes/hero1001.png' },
    { name: 'Yve', icon: 'img/heroes/hero1011.png' },
    { name: 'Mathilda', icon: 'img/heroes/hero1021.png' },
    { name: 'Paquito', icon: 'img/heroes/hero1031.png' },
    { name: 'Gloo', icon: 'img/heroes/hero1041.png' },
    { name: 'Beatrix', icon: 'img/heroes/hero1051.png' },
    { name: 'Phoveus', icon: 'img/heroes/hero1061.png' },
    { name: 'Natan', icon: 'img/heroes/hero1071.png' },
    { name: 'Aulus', icon: 'img/heroes/hero1081.png' },
    { name: 'Aamon', icon: 'img/heroes/hero1091.png' },
    { name: 'Valentina', icon: 'img/heroes/hero1101.png' },
    { name: 'Edith', icon: 'img/heroes/hero1111.png' },
    { name: 'Floryn', icon: 'img/heroes/hero1121.png' },
    { name: 'Yin', icon: 'img/heroes/hero1131.png' },
    { name: 'Melissa', icon: 'img/heroes/hero1141.png' },
    { name: 'Xavier', icon: 'img/heroes/hero1151.png' },
    { name: 'Julian', icon: 'img/heroes/hero1161.png' },
    { name: 'Fredrinn', icon: 'img/heroes/hero1171.png' },
    { name: 'Joy', icon: 'img/heroes/hero1181.png' },
    { name: 'Novaria', icon: 'img/heroes/hero1191.png' },
    { name: 'Arlott', icon: 'img/heroes/hero1201.png' },
    { name: 'Ixia', icon: 'img/heroes/hero1211.png' },
    { name: 'Nolan', icon: 'img/heroes/hero1221.png' },
    { name: 'Cici', icon: 'img/heroes/hero1231.png' },
    { name: 'Chip', icon: 'img/heroes/hero1241.png' },
    { name: 'Zhuxin', icon: 'img/heroes/hero1251.png' },
    { name: 'Suyou', icon: 'img/heroes/hero1261.png' },
    { name: 'Lukas', icon: 'img/heroes/hero1271.png' },
    { name: 'Kalea', icon: 'img/heroes/hero1281.png' },
    { name: 'Zetian', icon: 'img/heroes/hero1291.png' },
    { name: 'Obsidia', icon: 'img/heroes/hero1301.png' },
];

// Auto-verificación en consola
if (typeof console !== 'undefined') {
    console.log(`✅ heroIcons cargado: ${heroIcons.length} héroes disponibles`);
}

// Exportar para Node.js si es necesario
if (typeof module !== 'undefined' && module.exports) {
    module.exports = heroIcons;
}
